homeassistant:
  # Name of the location where Home Assistant is running
  name: HA
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  # Customization file
  customize: !include customize.yaml

# Enables Cloud Component
cloud:


# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv
    - samsung_tv
    - yamaha
# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

#ios:
#  push:
#    categories:
#      - name: Alarm
#        identifier: 'ALARM'
#        actions:
#          - identifier: 'SOUND_ALARM'
#            title: 'Sound Alarm'
#            activationMode: 'background'
#            authenticationRequired: yes
#            destructive: yes
#            behavior: 'default'
#          - identifier: 'SILENCE_ALARM'
#            title: 'Silence Alarm'
#            activationMode: 'background'
#            authenticationRequired: yes
#            destructive: no
#            behavior: 'textInput'
#            textInputButtonTitle: 'Silencio!'
#            textInputPlaceholder: 'Placeholder'





# Text to speech
tts:
  - platform: google

device_tracker:
  - platform: owntracks

mqtt:
  broker: 192.168.2.2
  port: 1883
  client_id: home-assistant
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant
  protocol: 3.1
  birth_message:
    topic: "tele/hass1/LWT"
    payload: "Online"
    qos: 1
    retain: true
  will_message:
    topic: "tele/hass1/LWT"
    payload: "Offline"
    qos: 1
    retain: true


panel_iframe:
  temp:
    title: 'Temp'
    url: 'http://www.meteocerdanyola.com/OutsideTemp.gif'
    icon: mdi:temperature-celsius
  humidity:
    title: 'Humidity'
    url: 'http://www.meteocerdanyola.com/OutsideHumidity.gif'
    icon: mdi:water-percent
  wind:
    title: 'Wind'
    url: 'http://www.meteocerdanyola.com/WindDirection.gif'
    icon: mdi:weather-windy

google_assistant:
  project_id: home-assistant-1a3a6
  client_id: EcNLemsdV0hEDGPwk4sR2byBNWRwRkNax4orE4alM0gwDzVgmfWrrclGS1pb6Hicl8ozYoB272FFHDw2
  access_token: gROml9IuqBO6gx50O3SSXmv2IyYUaIf71HxjEU5oH72fhmWRVgenQbR5HIWNxsAOYGolgAheQxAnu4k0
  #agent_user_id: [a string to identify user]
  #api_key: [a Homegraph API Key generated for the Google Actions project]

#  exposed_domains:
#    - switch
#    - light
#    - group





group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
light: !include lights.yaml
sensor: !include_dir_list sensors/
zone: !include zones.yaml
